---
openapi: 3.0.1
info:
  title: Documentation API V1
  version: v1
paths:
  "/api/v1/movies":
    get:
      summary: list movies
      tags:
      - Movies
      responses:
        '200':
          description: successful
    post:
      summary: create movie
      tags:
      - Movies
      parameters: []
      responses:
        '200':
          description: movie created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                annotation:
                  type: string
                durationInMinutes:
                  type: integer
                releaseDate:
                  type: string
                  format: date
              required:
              - name
  "/api/v1/movies/{id}":
    get:
      summary: show movie
      tags:
      - Movies
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: movie found
    put:
      summary: update movie
      tags:
      - Movies
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: movie updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                annotation:
                  type: string
                durationInMinutes:
                  type: integer
                releaseDate:
                  type: string
                  format: date
    delete:
      summary: destroy movie
      tags:
      - Movies
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: movie deleted
        '404':
          description: movie not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
