---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/movies":
    get:
      summary: list movies
      responses:
        '200':
          description: successful
  "/api/v1/movies/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show movie
      responses:
        '200':
          description: successful
servers:
- url: https://localhost:3000
  variables:
    defaultHost:
      default: https://localhost:3000
