default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "#{File.basename(Rails.root)}") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "#{File.basename(Rails.root)}") %>_test

production:
  <<: *default
